default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PORPOS_DATABASE_USERNAME"] %>
  password: <%= ENV["PORPOS_DATABASE_PASSWORD"] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: porpos_development


production:
  password: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: porpos_test
